// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yarp.Gateway.EntityFrameworkCore;

#nullable disable

namespace Yarp.Gateway.Migrations
{
    [DbContext(typeof(YarpDbContext))]
    partial class YarpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpActiveHealthCheckOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("HealthCheckOptionId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Interval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Policy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timeout")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckOptionId")
                        .IsUnique();

                    b.ToTable("YarpActiveHealthCheckOptions");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClusterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadBalancingPolicy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YarpClusters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bdfdc599-5306-45cf-8ad2-8b995e84801f"),
                            ClusterId = "cluster1"
                        },
                        new
                        {
                            Id = new Guid("f0fa724b-d1c6-4845-ac70-5ad59a860403"),
                            ClusterId = "cluster2"
                        });
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpDestination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClusterId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Health")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.ToTable("YarpDestinations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ede2881-92c4-4689-befc-2ef019c6ef60"),
                            Address = "http://localhost:5251",
                            ClusterId = new Guid("bdfdc599-5306-45cf-8ad2-8b995e84801f"),
                            Name = "Cluster1/Destination1"
                        },
                        new
                        {
                            Id = new Guid("20f20b36-9956-427c-b6b6-5b8cf711ca20"),
                            Address = "http://localhost:5252",
                            ClusterId = new Guid("f0fa724b-d1c6-4845-ac70-5ad59a860403"),
                            Name = "Cluster2/Destination2"
                        });
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpForwarderRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityTimeout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AllowResponseBuffering")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ClusterId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionPolicy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("YarpRequestProxyOptions");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpHealthCheckOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvailableDestinationsPolicy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClusterId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("YarpHealthCheckOptions");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpHttpClientOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClusterId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("DangerousAcceptAnyServerCertificate")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnableMultipleHttp2Connections")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxConnectionsPerServer")
                        .HasColumnType("int");

                    b.Property<string>("RequestHeaderEncoding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SslProtocols")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("YarpProxyHttpClientOptions");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hosts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Methods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RouteId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RouteId")
                        .IsUnique();

                    b.ToTable("YarpMatches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58d29d21-e1ec-4b25-8cfa-c06d164c6593"),
                            Path = "/api/first/{**catch-all}",
                            RouteId = new Guid("32e7f141-fa42-4cf0-ad09-9c50a1fe9e3b")
                        },
                        new
                        {
                            Id = new Guid("a15addda-c363-41df-90ff-20d7a35bf17b"),
                            Path = "/api/second/{**catch-all}",
                            RouteId = new Guid("1a5081de-6d33-468c-92e0-35c9522e01f4")
                        });
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClusterId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DestinationId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RouteId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("YarpClusterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("YarpDestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("YarpRouteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("RouteId");

                    b.HasIndex("YarpClusterId");

                    b.HasIndex("YarpDestinationId");

                    b.HasIndex("YarpRouteId");

                    b.ToTable("YarpMetadatas");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpPassiveHealthCheckOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("HealthCheckOptionId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Policy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReactivationPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckOptionId")
                        .IsUnique();

                    b.ToTable("YarpPassiveHealthCheckOptions");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorizationPolicy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClusterId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorsPolicy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<string>("RouteId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.ToTable("YarpRoutes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32e7f141-fa42-4cf0-ad09-9c50a1fe9e3b"),
                            AuthorizationPolicy = "Default",
                            ClusterId = new Guid("bdfdc599-5306-45cf-8ad2-8b995e84801f"),
                            RouteId = "route1"
                        },
                        new
                        {
                            Id = new Guid("1a5081de-6d33-468c-92e0-35c9522e01f4"),
                            ClusterId = new Guid("bdfdc599-5306-45cf-8ad2-8b995e84801f"),
                            RouteId = "route2"
                        });
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpRouteHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCaseSensitive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MatchId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Values")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("YarpRouteHeaders");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpRouteQueryParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCaseSensitive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Values")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("YarpRouteQueryParameter");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpSessionAffinityConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AffinityKeyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClusterId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("FailurePolicy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Policy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("YarpSessionAffinityOptions");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpSessionAffinityCookie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expiration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HttpOnly")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsEssential")
                        .HasColumnType("bit");

                    b.Property<string>("MaxAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SameSite")
                        .HasColumnType("int");

                    b.Property<int?>("SecurePolicy")
                        .HasColumnType("int");

                    b.Property<Guid?>("SessionAffinityConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SessionAffinityConfigId")
                        .IsUnique()
                        .HasFilter("[SessionAffinityConfigId] IS NOT NULL");

                    b.ToTable("YarpSessionAffinityCookie");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpSessionAffinityOptionSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YarpSessionAffinityOptionSettings");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpTransform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RouteId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("YarpTransforms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54475d14-1ef8-4bed-92b4-8bcb17505066"),
                            RouteId = new Guid("32e7f141-fa42-4cf0-ad09-9c50a1fe9e3b"),
                            Type = 4,
                            Value = "/api/{**catch-all}"
                        },
                        new
                        {
                            Id = new Guid("f994ad38-8eee-43f9-8001-6f418fd84455"),
                            RouteId = new Guid("32e7f141-fa42-4cf0-ad09-9c50a1fe9e3b"),
                            Type = 4,
                            Value = "/api/{**catch-all}"
                        });
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpWebProxyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("BypassOnLocal")
                        .HasColumnType("bit");

                    b.Property<Guid?>("HttpClientOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("UseDefaultCredentials")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HttpClientOptionId")
                        .IsUnique()
                        .HasFilter("[HttpClientOptionId] IS NOT NULL");

                    b.ToTable("YarpWebProxyConfig");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpActiveHealthCheckOption", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpHealthCheckOption", "HealthCheckOption")
                        .WithOne("Active")
                        .HasForeignKey("Yarp.Gateway.Entities.YarpActiveHealthCheckOption", "HealthCheckOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCheckOption");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpDestination", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpCluster", "Cluster")
                        .WithMany("Destinations")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpForwarderRequest", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpCluster", "Cluster")
                        .WithOne("HttpRequest")
                        .HasForeignKey("Yarp.Gateway.Entities.YarpForwarderRequest", "ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpHealthCheckOption", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpCluster", "Cluster")
                        .WithOne("HealthCheck")
                        .HasForeignKey("Yarp.Gateway.Entities.YarpHealthCheckOption", "ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpHttpClientOption", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpCluster", "Cluster")
                        .WithOne("HttpClient")
                        .HasForeignKey("Yarp.Gateway.Entities.YarpHttpClientOption", "ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpMatch", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpRoute", "Route")
                        .WithOne("Match")
                        .HasForeignKey("Yarp.Gateway.Entities.YarpMatch", "RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpMetadata", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpCluster", "Cluster")
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Yarp.Gateway.Entities.YarpDestination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Yarp.Gateway.Entities.YarpRoute", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Yarp.Gateway.Entities.YarpCluster", null)
                        .WithMany("Metadata")
                        .HasForeignKey("YarpClusterId");

                    b.HasOne("Yarp.Gateway.Entities.YarpDestination", null)
                        .WithMany("Metadata")
                        .HasForeignKey("YarpDestinationId");

                    b.HasOne("Yarp.Gateway.Entities.YarpRoute", null)
                        .WithMany("Metadata")
                        .HasForeignKey("YarpRouteId");

                    b.Navigation("Cluster");

                    b.Navigation("Destination");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpPassiveHealthCheckOption", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpHealthCheckOption", "HealthCheckOption")
                        .WithOne("Passive")
                        .HasForeignKey("Yarp.Gateway.Entities.YarpPassiveHealthCheckOption", "HealthCheckOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCheckOption");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpRoute", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpCluster", "Cluster")
                        .WithMany("ProxyRoutes")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpRouteHeader", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpMatch", "Match")
                        .WithMany("Headers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpRouteQueryParameter", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpMatch", "Match")
                        .WithMany("QueryParameters")
                        .HasForeignKey("MatchId");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpSessionAffinityConfig", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpCluster", "Cluster")
                        .WithOne("SessionAffinity")
                        .HasForeignKey("Yarp.Gateway.Entities.YarpSessionAffinityConfig", "ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpSessionAffinityCookie", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpSessionAffinityConfig", "SessionAffinityConfig")
                        .WithOne("Cookie")
                        .HasForeignKey("Yarp.Gateway.Entities.YarpSessionAffinityCookie", "SessionAffinityConfigId");

                    b.Navigation("SessionAffinityConfig");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpTransform", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpRoute", "Route")
                        .WithMany("Transforms")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpWebProxyConfig", b =>
                {
                    b.HasOne("Yarp.Gateway.Entities.YarpHttpClientOption", "HttpClientOption")
                        .WithOne("WebProxy")
                        .HasForeignKey("Yarp.Gateway.Entities.YarpWebProxyConfig", "HttpClientOptionId");

                    b.Navigation("HttpClientOption");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpCluster", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("HealthCheck")
                        .IsRequired();

                    b.Navigation("HttpClient")
                        .IsRequired();

                    b.Navigation("HttpRequest")
                        .IsRequired();

                    b.Navigation("Metadata");

                    b.Navigation("ProxyRoutes");

                    b.Navigation("SessionAffinity")
                        .IsRequired();
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpDestination", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpHealthCheckOption", b =>
                {
                    b.Navigation("Active")
                        .IsRequired();

                    b.Navigation("Passive")
                        .IsRequired();
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpHttpClientOption", b =>
                {
                    b.Navigation("WebProxy");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpMatch", b =>
                {
                    b.Navigation("Headers");

                    b.Navigation("QueryParameters");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpRoute", b =>
                {
                    b.Navigation("Match")
                        .IsRequired();

                    b.Navigation("Metadata");

                    b.Navigation("Transforms");
                });

            modelBuilder.Entity("Yarp.Gateway.Entities.YarpSessionAffinityConfig", b =>
                {
                    b.Navigation("Cookie");
                });
#pragma warning restore 612, 618
        }
    }
}
